//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChillNExplore.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Projet24Entities : DbContext
    {
        public Projet24Entities()
            : base("name=Projet24Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<joueur> joueurs { get; set; }
        public virtual DbSet<lieu> lieux { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<quizz> quizzs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ville> villes { get; set; }
    }
}
