//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChillNExplore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class joueur
    {
        public string idjoueur { get; set; }
        public string idville { get; set; }
        public string pseudo { get; set; }
        public string photo { get; set; }
        public Nullable<System.DateTime> datenaissance { get; set; }
    
        public virtual ville ville { get; set; }
    }
}
