//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChillNExplore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class lieu
    {
        public string idlieu { get; set; }
        public string idquizz { get; set; }
        public string idville { get; set; }
        public string nom { get; set; }
        public string type { get; set; }
        public string pos { get; set; }
        public string photo { get; set; }
    
        public virtual quizz quizz { get; set; }
        public virtual ville ville { get; set; }
    }
}
