//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChillNExplore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public string idquestion { get; set; }
        public string idquizz { get; set; }
        public string intitule { get; set; }
        public string image { get; set; }
        public string réponse { get; set; }
        public string indice { get; set; }
    
        public virtual quizz quizz { get; set; }
    }
}
